Add validation_util module for URL validation and update urlgennwm.py #43
CIROH-UA/nwmurl pull request #47
Opened 2024-01-22 21:59 UTC by manjirigunaji

This pull request introduces a new module, validation_util.py, to handle URL validation within the National Water Model (NWM) utility scripts. The validation_util module includes a check_valid_urls function that validates URLs and filters out any invalid ones, reducing dependencies on tqdm

2024-01-22 22:30 UTC, jameshalgren commented
Please post a few results from tests demonstrating the new function.

2024-02-06 19:32 UTC, jameshalgren requested changes, later dismissed
Thank you for the PR! 
Please 
- [ ] correct the accidental deletions. 
- [ ] add the string to the test readme to obtain the test output indicated (also, please put this same information in the PR thread to facilitate review.)
- [ ] consider including a standard unit test for the validation script. 

Thanks! 

@karnesh Please watch for this updated PR.

2024-02-06 19:32 UTC, jameshalgren commented on nwmurl/urlgennwm.py
> -retrospective_var_types = {
These deletions look accidental.

2024-02-06 19:32 UTC, jameshalgren commented on nwmurl/Readme_validation_testcase.txt
> +Here's an example of the test case output:
Can you add the command line string to obtain this test?

2024-02-13 16:08 UTC, karnesh requested changes
Thank you for updating the PR! @manjirigunaji 

- Please clean up the code and remove same functions in urlgennwm.py and validation_util.py.
- Please post few results demonstrating the new function.
- It would be better to have a unit test instead of hard coded test - this can be either done now or in an another PR.

Thanks!

2024-02-23 16:15 UTC, manjirigunaji commented on nwmurl/urlgennwm.py
> +valid_files = check_valid_urls(file_list)
![Test](https://github.com/CIROH-UA/nwmurl/assets/43341658/ef0da3eb-3c88-4a05-88b3-31e68cfd5fae)
I have included a testing demo image that could be beneficial.

2024-02-26 22:07 UTC, manjirigunaji commented on nwmurl/urlgennwm.py
> +valid_files = check_valid_urls(file_list)
The above is an  image  that is the filenamelist.txt.
![image](https://github.com/CIROH-UA/nwmurl/assets/43341658/c35fcd48-33f8-4239-969e-1a69ce1c3782)

2024-03-06 16:37 UTC, karnesh approved these changes
Thanks for updating the PR @manjirigunaji. Please change the hard coded test to a unit test in another PR. @sepehrkrz Please feel free to merge the PR.

2024-04-24 15:50 UTC, karnesh approved these changes
It looks good and this PR can be merged.

2025-08-14 21:40 UTC, arpita0911patel approved these changes

2025-08-14 21:41 UTC, merged

2025-10-17 14:49 UTC, jameshalgren commented
This PR introduced some dependency collisions. Adding an issue for additional unit tests handling that -- @karnesh